import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Logo from "@/components/layouts/Logo";
import AppLinks from "@/components/layouts/AppLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="h-[160px] px-[100px] bg-white border-b border-gray-300 flex justify-between items-center">
          <Logo />
          <AppLinks />
        </header>
        <main className="bg-gray-100 px-[100px] flex-grow">{children}</main>
      </body>
    </html>
  );
}
